wildcatMicroFund/Areas/Admin/Controllers/AdminReviewApplications/AdminReviewApplicationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using wildcatMicroFund.Areas.Admin.ViewModels;
using wildcatMicroFund.Areas.Mentor.ViewModels;
using wildcatMicroFund.Interfaces;
using wildcatMicroFund.Models;

[Area("Admin")]
public class AdminReviewApplicationsController : Controller
{
    [BindProperty]
    public ReviewApplicationVM ReviewApplicationObj { get; set; }

    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;
    public AdminReviewApplicationsController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)//Dependency Injection & path to wwwroot folder
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
    }


    public ViewResult Index()
    {
        IEnumerable<ApplicationStatus> AdminReviewApplication = _unitOfWork.ApplicationStatus.List(null, null, "Application,Status");//WHERE, ORDERBY, JOIN
        return View(AdminReviewApplication);
    }

    [HttpGet]
    public IActionResult Upsert(int? id, int? appId) //optional id needed with edit mode vs create
    {
        
        var stati = _unitOfWork.Status.List();

        ReviewApplicationObj = new ReviewApplicationVM
        {
            ReviewApplication = new ApplicationStatus(),            
            Application = _unitOfWork.Application.Get(a => a.Id == appId),
            Status = _unitOfWork.Status.Get(s => s.StatusID == id),
            StatusList = stati.Select(f => new SelectListItem { Value = f.StatusID.ToString(), Text = f.StatusDesc })
        };

        if (id != null)
        {
            ReviewApplicationObj.ReviewApplication = _unitOfWork.ApplicationStatus.Get(u => u.AppStatId == id, true);
            if (ReviewApplicationObj == null)
            {
                return NotFound();
            }
        }

        return View(ReviewApplicationObj);
    }

    [HttpPost]
    public IActionResult Upsert()
    {

        if (!ModelState.IsValid)
        {
            return View();
        }
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
        
        ReviewApplicationObj.ReviewApplication.StatusDate = DateTime.Now;
        ReviewApplicationObj.ReviewApplication.UserID = claim.Value;
        _unitOfWork.ApplicationStatus.Update(ReviewApplicationObj.ReviewApplication);

        _unitOfWork.Commit();
        return RedirectToAction("Index");
    }
}

wildcatMicroFund/Areas/Admin/Views/AdminReviewApplications/Index.cshtml
@model IEnumerable<ApplicationStatus>

@{ViewData["Title"] = "Review Application";}

<div class="container p-3">
    @*Header*@
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Application List</h2>
        </div>
    </div>
    <br/>

    @*Filter tabs*@
    <div style="background-color:aquamarine; width:0px; white-space:nowrap;">
        <span class="btn btn-primary" id="all-btn">All</span>
        <span class="btn btn-primary" id="new-btn">New</span>
        <span class="btn btn-primary" id="ready-btn">Ready for Pitch Event</span>
    </div>
    <br/>

    @*Application information*@
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Application</th>
                <th>Entrepreneur</th>
                <th>Mentor</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr class="info-row status-@{WriteLiteral(@obj.Status.StatusDesc.ToLower().Replace(' ', '-'));}">
                    <td>@obj.Application.CompanyName</td>

                    <td>@*Entrepreneur Name Here*@</td>

                    <td>@*Mentor Name Here*@</td>

                    <td style="width:0px; white-space:nowrap;">
                        @if (@obj.Status.StatusDesc == "Submitted") @*Highlight whatever statuses you want here*@
                        {
                            <span style="font-weight:bolder; color:mediumslateblue">NEW</span>
                        }
                        else 
                        {
                            <span>@obj.Status.StatusDesc</span>
                        }
                    </td>

                    <td style="width:0px; white-space:nowrap; text-align:center">
                        @*Actions*@
                        <a asp-controller="AdminReviewApplications" asp-action="Upsert" asp-route-id="@obj.AppStatId" asp-route-appId="@obj.Application.Id" class="btn btn-primary mx-2">
                            @if (@obj.Status.StatusDesc == "Submitted")
                            {
                                <span>Review</span>
                            }
                            else 
                            {
                                <span>View</span>
                            }
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    const rows = document.getElementsByClassName('info-row');
    const allButton = document.getElementById('all-btn');
    const newButton = document.getElementById('new-btn');
    const rdyButton = document.getElementById('ready-btn');

    // Show all applications
    function showAll() {
        for (var i = 0; i < rows.length; i++) {
            rows.item(i).style.display = "";
        }
    }
    allButton.addEventListener("click", showAll);

    // Only show newly submitted applications
    function showNew() {
        for (var i = 0; i < rows.length; i++) {
            if (rows.item(i).className.includes("status-submitted")) {
                rows.item(i).style.display = "";
            } else {
                rows.item(i).style.display = "none";
            }
        }
    }
    newButton.addEventListener("click", showNew);

    // Only show applications that need to be assigned to a pitch event
    function showRdy() {
        for (var i = 0; i < rows.length; i++) {
            if (rows.item(i).className.includes("status-ready-for-pitch-event")) {
                rows.item(i).style.display = "";
            } else {
                rows.item(i).style.display = "none";
            }
        }
    }
    rdyButton.addEventListener("click", showRdy);

    window.addEventListener("load", showAll);
</script>

wildcatMicroFund/Areas/Admin/Views/AdminReviewApplications/Upsert.cshtml
@model wildcatMicroFund.Areas.Mentor.ViewModels.ReviewApplicationVM
@{
    ViewData["Title"] = "Update Application";
}
<form method="post" asp-controller="AdminReviewApplications" asp-action="Upsert" enctype="multipart/form-data">
    <div class="container">
        <div class="row px-2 mx-2 backgroundWhite border">
            @* All for Model validation and HTML validation *@
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="col-12 px-3" style="border-bottom:1px solid #325d88">
                <h2 class="text-primary">Update Application</h2>
            </div>
            <div class="col-8 pt-3 offset-3">
                <div class="form-group row m-2">
                    <div class="col-4">
                        <h3>Company Name</h3>
                    </div>
                    <div class="col-3">
                           <h3>@Model.Application.CompanyName</h3>
                    </div>
                </div>
                
                <div class="form-group row ">
                    <div class="col-9">
                        @*These hide the values from the user, but allow the update button to pass the values back through the VM object*@
                        <input readonly type="hidden" asp-for="ReviewApplication.AppStatId" />
                        <input readonly type="hidden" asp-for="ReviewApplication.ApplicationId" />
                        <input readonly type="hidden" asp-for="ReviewApplication.UserID" />
                        <input readonly type="hidden" asp-for="ReviewApplication.StatusDate" />
                    </div>
                </div>

                <div class="form-group row m-2">
                    <div class="col-4">
                        <label asp-for="ReviewApplication.StatusId"></label>
                    </div>
                    <div class="col-5">
                        @Html.DropDownListFor(m => m.ReviewApplication.StatusId,
                        Model.StatusList,
                        " - Please select a new status - ",
                        new { @class = "form-control", @id="ddlStatus" })
                        <span class="text-danger" asp-validation-for="ReviewApplication.StatusId"></span>
                    </div>
                </div>
                <div class="form-group row m-2">
                    <div class="col-9" style="border-top:1px solid #325d88">
                        <div class="row m-2">
                            <div class="col-6">
                                <button type="submit" class="btn btn-primary form-control">Update</button>
                                                               
                            </div>
                            <div class="col-6">
                                <a asp-controller="AdminReviewApplications" asp-action="Index" class="btn btn-success form-control">Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        </div>
    </div>
</form>