wildcatMicroFund/Areas/Entrepreneur/Controllers/NewApplication/NewApplicationController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using wildcatMicroFund.Interfaces;
using wildcatMicroFund.Models;

[Area("Entrepreneur")]
public class NewApplicationController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public NewApplicationController(IUnitOfWork unitOfWork)//Dependency Injection
    {
        _unitOfWork = unitOfWork;

    }

    public ViewResult Index()
    {
        var claimID = (ClaimsIdentity)User.Identity;
        var claim = claimID.FindFirst(ClaimTypes.NameIdentifier);
        
        var appList = _unitOfWork.UserAssignment.List(a => a.User.Id == claim.Value, a => a.UserAssignmentID, "Application");
        return View(appList);

    }

    public ViewResult ApplicationForm()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Application obj)
    {

        if (ModelState.IsValid)
        {
            // User data
            var claimID = (ClaimsIdentity)User.Identity;
            var claim = claimID.FindFirst(ClaimTypes.NameIdentifier);

            obj.AppStatus = _unitOfWork.Status.Get(a => a.StatusID == 1).StatusID;  // sets the Application Status as 'submitted'
            
            _unitOfWork.Application.Add(obj); //internal add

            // New UserAssignment entry created to tie Application and User
            var _UserAssignment = new UserAssignment();
            _UserAssignment.Application = _unitOfWork.Application.Get(a => a.CompanyName == obj.CompanyName && a.CreatedDate == obj.CreatedDate); // Get ApplicationID from application table
            _UserAssignment.User = _unitOfWork.ApplicationUser.Get(a => a.Id == claim.Value);   // Get User object from users table
            _UserAssignment.ApplicationAssignmentType = _unitOfWork.UserApplicationAssignmentType.GetById(4);   // Set App assignment type to Entrepreneur

            _unitOfWork.UserAssignment.Add(_UserAssignment); // internal add

            // Inserting new entry into ApplicationStatus table
            var _AppStatus = new ApplicationStatus();
            _AppStatus.UserID = claim.Value;    // This takes just a userID instead of a user object, so claim.Value is just used here
            _AppStatus.ApplicationId = _UserAssignment.Application.Id;   // Pull Application ID from _UserAssignment since already queried
            _AppStatus.StatusId = obj.AppStatus;    // Already pulled statusID for obj...
            _AppStatus.StatusDate = DateTime.Now;   // pretty self explanitory...

            _unitOfWork.ApplicationStatus.Add(_AppStatus);


            _unitOfWork.Commit(); //physical commit to DB table
            TempData["success"] = "Application created Successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }
}

wildcatMicroFund/Areas/Entrepreneur/Views/NewApplication/Index.cshtml
@{
    ViewData["Title"] = "New Applications";
}

<div class="text-center">
    <h1 class="display-4">Getting Started: </h1>
    <p class="py-2">We are happy to see that you are applying for the Wildcat Micro Fund! Please fill out the form below accurately...</p>
    <p>
        Lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor lorem ipsum dolor 
        lorem ipsum dolorlorem ipsum dolorlorem ipsum dolorlorem ipsum dolor lorem ipsum dolorlorem ipsum dolor lorem ipsum dolorlorem ipsum dolor
    </p>
    
    <h2 class="display-5 pb-3">To fill out a new application, click the link below!</h2>
    <div class="row row-cols-5">
        <div class="col-2"></div>
        <a class="col-3 btn btn-primary" asp-controller="NewApplication" asp-action="ApplicationForm">New application</a>
        <div class="col-2"></div>
        <a class="col-3 btn btn-secondary">Back to Home</a>
        <div class="col-2"></div>
    </div>

    <div class="row py-3">
        <h1 class="Display-5 row">Your applications:</h1>

        @foreach (var item in Model)
        {
            <div class="card col-2">
                <p class="card-header">@(item.Application.CompanyName)</p>
                @*<p class="card-body">@(item.Application.AppStatus)</p> ViewModel breaks everything, will be taken care of shortly*@
                <p class="card-footer">@(item.Application.CreatedDate)</p>
            </div>
        }
        
        
    </div>
</div>