wildcatMicroFund/Areas/Mentor/Controllers/ReviewApplications/ReviewApplicationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using wildcatMicroFund.Areas.Mentor.ViewModels;
using wildcatMicroFund.Interfaces;
using wildcatMicroFund.Models;

[Area("Mentor")]
public class ReviewApplicationsController : Controller
{
    [BindProperty]
    public ReviewApplicationVM ReviewApplicationObj { get; set; }

    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;
    public ReviewApplicationsController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)//Dependency Injection & path to wwwroot folder
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
    }


    public ViewResult Index()
    {
        
        IEnumerable<ApplicationStatus> ReviewApplication = _unitOfWork.ApplicationStatus.List(r => r.Status.StatusID == 2 || r.Status.StatusID == 5, r => r.Application.Id, "Application,Status");//WHERE, ORDERBY, JOIN
        return View(ReviewApplication);
    }

    [HttpGet]
    public IActionResult Upsert(int? id, int? appId, int? statId) //optional id needed with edit mode vs create
    {
        
        var stati = _unitOfWork.Status.List();
        var mentorList = _unitOfWork.ApplicationUser.List();
        var judgeList = _unitOfWork.ApplicationUser.List();

        var ent = _unitOfWork.UserAssignment.Get(e => e.ApplicationAssignmentType.UserApplicationAssignmentDesc == "Entrepreneur" && e.Application.Id == appId);
        var mentor = _unitOfWork.UserAssignment.Get(m => m.ApplicationAssignmentType.UserApplicationAssignmentDesc == "Mentor" && m.Application.Id == appId);
        //var judge = _unitOfWork.UserAssignment.Get(j => j.ApplicationAssignmentType.UserApplicationAssignmentDesc == "Judge" && j.Application.Id == appId);
        var appStatus = new ApplicationStatus();
        var app = _unitOfWork.Application.Get(a => a.Id == appId);
        var status = _unitOfWork.Status.Get(s => s.StatusID == statId);
        //var userAssignment = _unitOfWork.UserApplicationAssignmentType.Get(u => u.UserApplicationAssignmentTypeId == ent.ApplicationAssignmentType.UserApplicationAssignmentTypeId);

        ReviewApplicationObj = new ReviewApplicationVM
        {
            
            UserAssignment = new UserAssignment(),
            Entrepreneur = _unitOfWork.ApplicationUser.Get(e => e.Id == ent.User.Id),
            Mentor = (mentor.UserAssignmentID == null ? null : _unitOfWork.ApplicationUser.Get(m=> m.Id == mentor.User.Id)),
            //Judge = judge,
            ApplicationStatus = appStatus,
            Application = app,
            Status = _unitOfWork.Status.Get(s => s.StatusID == statId),
            StatusList = stati.Select(f => new SelectListItem { Value = f.StatusID.ToString(), Text = f.StatusDesc }),
            MentorList = mentorList.Select(m => new SelectListItem { Value = m.Id.ToString(), Text=m.FullName.ToString() })

            
        };

        if (id != null)
        {
            //ReviewApplicationObj.Entrepreneur = _unitOfWork.ApplicationUser.Get(u => u. == id, true);
            if (ReviewApplicationObj == null)
            {
                return NotFound();
            }
        }

        return View(ReviewApplicationObj);
    }

    [HttpPost]
    public IActionResult Upsert()
    {
        
        if (!ModelState.IsValid)
        {
            return View();
        }

                                        
        _unitOfWork.UserAssignment.Update(ReviewApplicationObj.UserAssignment);
        
        _unitOfWork.Commit();
        return RedirectToAction("Index");
    }
}

wildcatMicroFund/Areas/Mentor/Views/ReviewApplications/Index.cshtml
@model IEnumerable<ApplicationStatus>

@{
    ViewData["Title"] = "Review Application";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Application List</h2>
        </div>
    </div>
    <br /><br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Company Name
                </th>
                <th>
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Application.CompanyName
                    </td>                    
                    <td width="40%">
                        @obj.Status.StatusDesc
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="ReviewApplications" asp-action="Upsert" asp-route-id="@obj.AppStatId" asp-route-appId="@obj.Application.Id" asp-route-statId="@obj.Status.StatusID"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i>Review</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

wildcatMicroFund/Areas/Mentor/Views/ReviewApplications/Upsert.cshtml
@model wildcatMicroFund.Areas.Mentor.ViewModels.ReviewApplicationVM
@{
    ViewData["Title"] = "Update Application";
}
<form method="post" asp-controller="ReviewApplications" asp-action="Upsert" enctype="multipart/form-data">
    <div class="container">
        <div class="row px-2 mx-2 backgroundWhite border">
            @* All for Model validation and HTML validation *@
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="col-12 px-3" style="border-bottom:1px solid #325d88">
                <h2 class="text-primary">Update Application</h2>
            </div>
            <div class="col-8 pt-3 offset-3">
                <div class="form-group row m-2">
                    <div class="col-4">
                        <h3>Company Name</h3>
                    </div>
                    <div class="col-3">
                           <h3>@Model.Application.CompanyName</h3>
                    </div>
                </div>
                <div class="form-group row m-2">
                    <div class="col-4">
                        <h4>Entrepreneur</h4>
                    </div>
                    <div class="col-3">
                        <h4>@Model.Entrepreneur.FullName</h4>
                    </div>
                </div>
                <div class="form-group row m-2">
                    <div class="col-4">
                        <h4>Mentor</h4>
                    </div>
                    <div class="col-5">
                        <h4>@(Model.Mentor.FullName == "" ? "None" : Model.Mentor.FullName)</h4>
                    </div>
                </div>
                <div class="form-group row m-2">
                    <div class="col-4">
                        <h4>Judge</h4>
                    </div>
                    <div class="col-3">
                        <h4>@Model.Judge</h4>
                    </div>
                </div>
                
                <div class="form-group row ">
                    <div class="col-9">
                        @*These hide the values from the user, but allow the update button to pass the values back through the VM object*@
                        <input readonly type="hidden" asp-for="ApplicationStatus.AppStatId" />
                        <input readonly type="hidden" asp-for="ApplicationStatus.ApplicationId" />
                        <input readonly type="hidden" asp-for="ApplicationStatus.UserID" />
                        <input readonly type="hidden" asp-for="ApplicationStatus.StatusDate" />
                        <input readonly type="hidden"  asp-for="Application.CompanyName" />
                        
@*                        <input readyonly type="hidden" asp-for="ReviewApplication." />

                        [Key]
                        public int AppStatId { get; set; }
                        public int UserID { get; set; }

                        [Display(Name = "StatusDate")]
                        public DateTime StatusDate { get; set; }

*@                    </div>
                </div>

                <div class="form-group row m-2">
                    <div class="col-4">
                        <label asp-for="ApplicationStatus.StatusId"></label>
                    </div>
                    <div class="col-5">
                        @Html.DropDownListFor(m => m.ApplicationStatus.StatusId,
                        Model.StatusList,
                        " - Please select a new status - ",
                        new { @class = "form-control", @id="ddlStatus" })
                        <span class="text-danger" asp-validation-for="ApplicationStatus.StatusId"></span>

                    </div>
                </div>
                <div class="form-group row m-2">
                    <div class="col-9" style="border-top:1px solid #325d88">
                        <div class="row m-2">
                            <div class="col-6">
                                <button type="submit" class="btn btn-primary form-control">Update</button>
                                                               
                            </div>
                            <div class="col-6">
                                <a asp-controller="ReviewApplications" asp-action="Index" class="btn btn-success form-control">Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        </div>
    </div>
</form>